### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by eppinger** [sjdaniels/coldbox-recaptcha-module#1]
The modul defines no custom nameSpace in the modul Config, so the default nameSpace will be the module name in this case **recaptcha**

In coldbox 4.3 and up the the coldbox config setting will be loaded and after that the modules. And every module will be registered with his namespace in the config atruct.

The problem with the original documentation is, that the key **recaptcha** will be overwritten.

With this syntax, these configs will be merged
```
moduleSettings[ 'recaptcha' ] = {
	    private_key = "XXX",
	    public_key = "YYY"
};
```

**Comment by sjdaniels** [comment]
Fixed in PR from @lmajano, correct?

**Comment by eppinger** [comment]
yes
